const $$=(s,ctx=document)=>[...ctx.querySelectorAll(s)];
const nav=document.querySelector('.nav'), menu=document.querySelector('.menu'), navlinks=document.getElementById('navlinks');
menu?.addEventListener('click',()=>{const open=navlinks.classList.toggle('open');menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',open)});
$$('#navlinks a').forEach(a=>a.addEventListener('click',()=>{navlinks.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>20));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>obs.observe(el));
const layers={foundation:{k:'FOUNDATION',t:'Who owns what.',c:'Clear roles, responsibilities, reporting lines and accountability so everyone knows where ownership sits.',l:['Organisational structure','Roles & responsibilities','Accountability systems']},process:{k:'PROCESS',t:'How work gets done.',c:'Documented workflows and SOPs make important work more consistent and less dependent on memory.',l:['Standard operating procedures','Workflows','Checklists & procedures']},oversight:{k:'OVERSIGHT',t:'Know whether it is working.',c:'Leadership needs visibility into performance so problems can be identified before they become normal.',l:['Performance tracking','Reporting systems','Monitoring frameworks']}};
$$('.layer').forEach(b=>b.addEventListener('click',()=>{const d=layers[b.dataset.layer];$$('.layer').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('layer-kicker').textContent=d.k;document.getElementById('layer-title').textContent=d.t;document.getElementById('layer-copy').textContent=d.c;document.getElementById('layer-list').innerHTML=d.l.map(x=>`<li>${x}</li>`).join('')}));
const systems={structure:{k:'BUSINESS STRUCTURE',t:'Make ownership visible.',c:'We design the structure that brings clarity to who does what, who reports to whom and where accountability sits.',s:'Blurred ownership and founder bottlenecks.',b:'Roles, responsibilities, reporting and accountability structures.',a:'Decisions and responsibilities stop floating.'},operations:{k:'OPERATIONAL SYSTEMS',t:'Make good work repeatable.',c:'We turn important work into documented workflows that can be understood and followed consistently.',s:'Repeated mistakes and work that exists only in people’s heads.',b:'SOPs, workflows, checklists and operational procedures.',a:'The business has a clearer, repeatable way of doing critical work.'},management:{k:'MANAGEMENT SYSTEMS',t:'Turn activity into visibility.',c:'We create practical ways for leadership to see performance, track work and strengthen accountability.',s:'Reactive management and poor visibility into what is happening.',b:'Performance tracking, reporting systems and monitoring frameworks.',a:'Leadership can see what needs attention instead of discovering problems late.'},growth:{k:'GROWTH SYSTEMS',t:'Build for more than today.',c:'Growth should not automatically mean more dependence on the founder. We build structures that support delegation and continuity.',s:'Growth that increases pressure instead of creating capacity.',b:'Scalable processes, delegation structures and business continuity systems.',a:'The business is better positioned to grow without constant founder intervention.'}};
$$('.system-tab').forEach(b=>b.addEventListener('click',()=>{const d=systems[b.dataset.system];$$('.system-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');[['system-kicker','k'],['system-title','t'],['system-copy','c'],['solve','s'],['build','b'],['change','a']].forEach(([id,key])=>document.getElementById(id).textContent=d[key])}));
const steps=$$('.process-step');const stepObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){steps.forEach(x=>x.classList.remove('active'));e.target.classList.add('active')}}),{threshold:.65});steps.forEach(s=>stepObs.observe(s));
const modal=document.getElementById('booking');$$('[data-book]').forEach(b=>b.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');modal.querySelector('.close').focus()}));modal.querySelector('.close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
const questions=['Could your team complete their core tasks if you disappeared for two weeks?','Are responsibilities clearly defined?','Do your key processes exist outside people’s heads?','Can you easily tell what is working and what is not?','Do you know exactly who owns each critical business function?'];let q=0,score=0;const qEl=document.getElementById('question'),count=document.getElementById('qcount'),bar=document.querySelector('.progress span'),answers=document.querySelector('.answers'),result=document.getElementById('quiz-result');answers.addEventListener('click',e=>{if(!e.target.matches('[data-answer]'))return;score+=e.target.dataset.answer==='yes'?2:e.target.dataset.answer==='sometimes'?1:0;q++;if(q<questions.length){qEl.textContent=questions[q];count.textContent=`QUESTION ${q+1} OF ${questions.length}`;bar.style.width=`${(q+1)/questions.length*100}%`}else showResult()});function showResult(){let title,copy;if(score<=3){title='SYSTEM DEPENDENT';copy='Important work appears to rely heavily on specific people and founder involvement. Your business may benefit from stronger foundations and documented ways of working.'}else if(score<=7){title='SYSTEM DEVELOPING';copy='Your business has elements of structure, but important work may still depend too heavily on specific people. There is room to strengthen consistency and oversight.'}else{title='SYSTEM READY';copy='You appear to have meaningful elements of structure. The next opportunity may be strengthening, connecting and improving the systems as the business grows.'}document.getElementById('result-title').textContent=title;document.getElementById('result-copy').textContent=copy;result.classList.add('show');document.querySelector('.quiz-side').style.display='none'}document.getElementById('restart').addEventListener('click',()=>{q=0;score=0;qEl.textContent=questions[0];count.textContent='QUESTION 1 OF 5';bar.style.width='20%';result.classList.remove('show');document.querySelector('.quiz-side').style.display='block'});document.getElementById('year').textContent=new Date().getFullYear();
