const $$=(s,c=document)=>[...c.querySelectorAll(s)], $=(s,c=document)=>c.querySelector(s);
// mobile nav
const menu=$('.menu'), nav=$('.nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});$$('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
// reveal
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
// modal
const modal=$('#bookModal');$$('[data-book]').forEach(b=>b.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('.close',modal).focus()}));$('.close').addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
// framework
const frameworkData={foundation:{label:'FOUNDATION',title:'Give the business a clear operating structure.',text:'Roles, responsibilities, reporting relationships and accountability should not be assumed. We make them visible.',items:['Roles & responsibilities','Reporting structures','Accountability systems']},process:{label:'PROCESS',title:'Turn important work into repeatable ways of working.',text:'We document how work moves so quality does not depend on memory or individual interpretation.',items:['SOPs','Workflows','Checklists']},oversight:{label:'OVERSIGHT',title:'Make performance visible to leadership.',text:'A system needs feedback. We build ways to track what is happening and identify where attention is needed.',items:['Performance tracking','Reporting systems','Monitoring frameworks']}};
$$('[data-layer]').forEach(b=>b.addEventListener('click',()=>{const d=frameworkData[b.dataset.layer];$$('[data-layer]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#frameworkDetail').innerHTML=`<p class="eyebrow">${d.label}</p><h3>${d.title}</h3><p>${d.text}</p><div>${d.items.map(i=>`<span>${i}</span>`).join('')}</div>`}));
// systems
const systems={structure:['BUSINESS STRUCTURE','Make ownership impossible to misunderstand.','Confusion about responsibility, reporting and decision-making.','Organisational structures, role definitions, accountability and reporting structures.','People know what they own—and leadership knows where accountability sits.'],operations:['OPERATIONAL SYSTEMS','Turn recurring work into a reliable process.','Repeated mistakes, forgotten steps and inconsistent execution.','SOPs, workflows, checklists and operational procedures.','Work becomes easier to repeat, teach and improve.'],management:['MANAGEMENT SYSTEMS','See what is working without managing by guesswork.','Invisible performance and reactive management.','Performance tracking, reporting systems, monitoring frameworks and accountability mechanisms.','Leadership has clearer signals for action.'],growth:['GROWTH SYSTEMS','Build capacity before growth exposes the gaps.','A business becoming more dependent on the founder as it grows.','Scalable processes, delegation structures and business continuity systems.','The organisation can carry more without one person carrying everything.']};
$$('[data-system]').forEach(b=>b.addEventListener('click',()=>{const d=systems[b.dataset.system];$$('[data-system]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#systemContent').innerHTML=`<p class="eyebrow">${d[0]}</p><h3>${d[1]}</h3><p><b>What it solves:</b> ${d[2]}</p><p><b>What we build:</b> ${d[3]}</p><p><b>What changes:</b> ${d[4]}</p>`}));
// process
const stages=[['01 / DIAGNOSE','Understand how the business actually works today.','Before building anything, we examine the current reality: how work moves, where decisions sit, what depends on whom and where friction appears.'],['02 / MAP','Find the gaps, bottlenecks and dependencies.','We make the current operating picture visible so the business can see what is connected, missing or creating unnecessary friction.'],['03 / DESIGN','Build the system the business actually needs.','We translate the diagnosis into structures, workflows and practical mechanisms designed around the reality of the organisation.'],['04 / IMPLEMENT','Move the system from paper into practice.','A system only matters when people can use it. We focus on making the design understandable and operational.'],['05 / OPTIMISE','Refine what the business learns in motion.','Systems are strengthened through use. We identify what needs adjustment and improve the operating model over time.']];$$('.stage').forEach(b=>b.addEventListener('click',()=>{const d=stages[b.dataset.stage];$$('.stage').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#stagePanel').innerHTML=`<span>${d[0]}</span><h3>${d[1]}</h3><p>${d[2]}</p>`}));
// diagnostic
const questions=[['Could your team complete their core tasks if you disappeared for two weeks?',['Yes, consistently',2],['Mostly, but some things would stop',1],['No, I would need to stay involved',0]],['Are responsibilities clearly defined?',['Yes',2],['Partly',1],['Not really',0]],['Do key processes exist outside people\'s heads?',['Yes, clearly documented',2],['Some do',1],['No',0]],['Can you easily tell what is working and what is not?',['Yes',2],['Sometimes',1],['Not easily',0]],['Do you know who owns each critical business function?',['Yes',2],['Mostly',1],['No',0]]];let qi=0,score=0;function renderQ(){if(qi>=questions.length){let label,text;if(score>=8){label='SYSTEM READY';text='You have meaningful structure in place. The next opportunity is strengthening consistency, visibility and the systems that support growth.'}else if(score>=4){label='SYSTEM DEVELOPING';text='Your business has elements of structure, but important knowledge or responsibility may still depend heavily on individuals.'}else{label='SYSTEM DEPENDENT';text='Your business appears to rely strongly on people, memory or constant founder involvement. Building structure could reduce operational fragility.'}$('#quiz').innerHTML=`<div class="result"><p class="eyebrow">YOUR RESULT</p><h3>${label}</h3><p>${text}</p><button class="btn light" data-book>Book a system <b>↗</b></button></div>`;return}const q=questions[qi];$('#quiz').innerHTML=`<div class="question active"><p class="q-number">QUESTION ${qi+1} OF ${questions.length}</p><h3>${q[0]}</h3><div class="answers">${q.slice(1).map((a,i)=>`<button class="answer" data-points="${a[1]}">${a[0]}</button>`).join('')}</div></div>`;$$('.answer',$('#quiz')).forEach(b=>b.addEventListener('click',()=>{score+=+b.dataset.points;qi++;renderQ()}))}renderQ();
// delegate result CTA
$('#quiz').addEventListener('click',e=>{if(e.target.closest('[data-book]')){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}});
